version: 0.2

phases:
  install:
    commands:
      - echo "Installing zip utility"
      - yum install -y zip

  build:
    commands:
      - echo "Zipping Lambda Function"
      - zip lambda.zip lambda_function.py

artifacts:
  files:
    - lambda.zip
