steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute",
        "instances",
        "start",
        "instance-20251116-191014",
        "--zone=us-central1-c"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
